version: "3.8"

networks:
  net:
    driver: bridge

services:
  intent-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
    container_name: nemo-en
    networks:
      - net
    #deploy:
  #      resources:
  #        limits:
  #          cpus: "0.1"
