version: "3.8"

networks:
  net:
    driver: bridge

services:
  nemo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    container_name: nemo-en
    networks:
      - net
        deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #deploy:
  #      resources:
  #        limits:
  #          cpus: "0.1"
