version: "3.8"

networks:
  net:
    driver: bridge

services:
  nemo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    container_name: nemo-hi
    networks:
      - net
    #deploy:
  #      resources:
  #        limits:
  #          cpus: "0.1"
