# Use NVIDIA CUDA base image
   FROM nvidia/cuda:11.6.2-base-ubuntu20.04

   # Install Python and pip
   RUN apt-get update && apt-get install -y python3-pip python3-dev
   RUN ln -s /usr/bin/python3 /usr/bin/python

   # Set the working directory in the container
   WORKDIR /app

   # Copy the current directory contents into the container at /app
   COPY . /app

   # Install any needed packages specified in requirements.txt
   COPY requirements.txt .
   RUN pip3 install --no-cache-dir -r requirements.txt

   # Make port 8000 available to the world outside this container
   EXPOSE 8000

   # Define environment variable for the model path
   ENV MODEL_PATH=/app/model

   # Run app.py when the container launches
   CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
   