version: "3.8"

networks:
  net:
    driver: bridge

services:
  speechbrain:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: speechbrain-li
    networks:
      - net
    #deploy:
  #      resources:
  #        limits:
  #          cpus: "0.1"
