version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_audio
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_test:/data/test

volumes:
  mongodb_data:
    driver: local
