version: "3.8"

networks:
  net:
    driver: bridge

services:
  spacy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: spacy-nlp
    networks:
      - net
    #deploy:
  #      resources:
  #        limits:
  #          cpus: "0.1"
