apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spacy
  template:
    metadata:
      labels:
        app: spacy
    spec:
      containers:
        - name: spacy
          image: <your_spacy_image>
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: spacy-service
spec:
  selector:
    app: spacy
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort
